// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Scratch.Infrastructure;

#nullable disable

namespace Scratch.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251215144403_UpdateSchema")]
    partial class UpdateSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("ProjectIdSequence")
                .IncrementsBy(100);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("KieuClaim");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("GiaTriClaim");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("IdVaiTro");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("VaiTroClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("KieuClaim");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("GiaTriClaim");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("IdNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NguoiDungClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("NhaCungCap");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("KhoaNhaCungCap");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("TenNhaCungCap");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("NguoiDungId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("NguoiDungDangNhap", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("IdNguoiDung");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("IdVaiTro");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("NguoiDung_VaiTro", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("IdNguoiDung");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("NhaCungCap");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("Ten");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("GiaTri");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("NguoiDungToken", (string)null);
                });

            modelBuilder.Entity("Scratch.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "ProjectIdSequence");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("IdDanhMuc");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NgayTao");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NgayXoa");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MoTa");

                    b.Property<string>("FileLink")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LinkFile");

                    b.Property<int>("LikeCount")
                        .HasColumnType("integer")
                        .HasColumnName("LuotThich");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Ten");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("IdCongKhai");

                    b.Property<string>("ThumbnailLink")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LinkAnh");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NgayCapNhat");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("IdNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DeletedAt")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("UserId");

                    b.ToTable("DuAn", (string)null);
                });

            modelBuilder.Entity("Scratch.Domain.Entities.ProjectBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("IdNguoiThucHien");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("MoTa");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("HieuLuc");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("IdDuAn");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Lydo");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("IdNguoiThuHoi");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NgayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("ByUserId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RevokedByUserId");

                    b.ToTable("CamDuAn", (string)null);
                });

            modelBuilder.Entity("Scratch.Domain.Entities.ProjectCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Ten");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NgayCapNhat");

                    b.HasKey("Id");

                    b.ToTable("DanhMucDuAn", (string)null);
                });

            modelBuilder.Entity("Scratch.Domain.Entities.ProjectComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NoiDung");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NgayTao");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("integer")
                        .HasColumnName("IdTraLoi");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("IdDuAn");

                    b.Property<Guid?>("RepliedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("IdNguoiTraLoi");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NgayCapNhat");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("IdNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RepliedUserId");

                    b.HasIndex("UserId");

                    b.ToTable("BinhLuanDuAn", (string)null);
                });

            modelBuilder.Entity("Scratch.Domain.Entities.ProjectLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NgayTao");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("IdDuAn");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NgayCapNhat");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("IdNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("LuotThichDuAn", (string)null);
                });

            modelBuilder.Entity("Scratch.Domain.Entities.ProjectReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("IdNguoiThucHien");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MoTa");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("IdDuAn");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Lydo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NgayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("ByUserId");

                    b.HasIndex("ProjectId");

                    b.ToTable("BaoCaoDuAn", (string)null);
                });

            modelBuilder.Entity("Scratch.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("MaDongBo");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Ten");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("TenChuanHoa");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("Scratch.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("SoLanDangNhapThatBai");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("MaDongBo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("XacNhanEmail");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("KhoaTaiKhoan");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ThoiGianKhoa");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("EmailChuanHoa");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("TenDangNhapChuanHoa");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("MatKhauHash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("SoDienThoai");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("XacNhanSoDienThoai");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("TokenLamMoi");

                    b.Property<DateTime?>("RefreshTokenExpriresAtUTC")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TokenLamMoi_ThoiHan");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("MaBaoMat");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("XacThucHaiLop");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NgayCapNhat");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("TenDangNhap");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("Scratch.Domain.Entities.UserBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("IdNguoiThucHien");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("MoTa");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("HieuLuc");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Lydo");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("IdNguoiThuHoi");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NgayCapNhat");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("IdNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("ByUserId");

                    b.HasIndex("RevokedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("CamNguoiDung", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Scratch.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Scratch.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Scratch.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Scratch.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scratch.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Scratch.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scratch.Domain.Entities.Project", b =>
                {
                    b.HasOne("Scratch.Domain.Entities.ProjectCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("Scratch.Domain.Entities.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Scratch.Domain.Entities.ProjectBan", b =>
                {
                    b.HasOne("Scratch.Domain.Entities.User", "ByUser")
                        .WithMany()
                        .HasForeignKey("ByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scratch.Domain.Entities.Project", "Project")
                        .WithMany("ProjectBans")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scratch.Domain.Entities.User", "RevokedByUser")
                        .WithMany()
                        .HasForeignKey("RevokedByUserId");

                    b.Navigation("ByUser");

                    b.Navigation("Project");

                    b.Navigation("RevokedByUser");
                });

            modelBuilder.Entity("Scratch.Domain.Entities.ProjectComment", b =>
                {
                    b.HasOne("Scratch.Domain.Entities.ProjectComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Scratch.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scratch.Domain.Entities.User", "RepliedUser")
                        .WithMany("RepliedComments")
                        .HasForeignKey("RepliedUserId");

                    b.HasOne("Scratch.Domain.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("Project");

                    b.Navigation("RepliedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Scratch.Domain.Entities.ProjectLike", b =>
                {
                    b.HasOne("Scratch.Domain.Entities.Project", "Project")
                        .WithMany("ProjectLikes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scratch.Domain.Entities.User", "User")
                        .WithMany("ProjectLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Scratch.Domain.Entities.ProjectReport", b =>
                {
                    b.HasOne("Scratch.Domain.Entities.User", "ByUser")
                        .WithMany()
                        .HasForeignKey("ByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scratch.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ByUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Scratch.Domain.Entities.UserBan", b =>
                {
                    b.HasOne("Scratch.Domain.Entities.User", "ByUser")
                        .WithMany()
                        .HasForeignKey("ByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scratch.Domain.Entities.User", "RevokedByUser")
                        .WithMany()
                        .HasForeignKey("RevokedByUserId");

                    b.HasOne("Scratch.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ByUser");

                    b.Navigation("RevokedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Scratch.Domain.Entities.Project", b =>
                {
                    b.Navigation("ProjectBans");

                    b.Navigation("ProjectLikes");
                });

            modelBuilder.Entity("Scratch.Domain.Entities.ProjectComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Scratch.Domain.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ProjectLikes");

                    b.Navigation("Projects");

                    b.Navigation("RepliedComments");
                });
#pragma warning restore 612, 618
        }
    }
}
